# DATA CLEANING

# i)Ctrgorical data

In [2]:
import pandas as pd

In [9]:
salary_data=pd.DataFrame({'Name':['Mani','Niswan','Sriram','Madesh'],'Salary':[20000,40000,60000,70000],
                          'Range':['Low','Mid','High','High']})

In [10]:
salary_data

Name  Salary Range
0    Mani   20000   Low
1  Niswan   40000   Mid
2  Sriram   60000  High
3  Madesh   70000  High

In [11]:
sal_data=pd.DataFrame({'Salary':[20000,40000,60000,70000],
                          'Range':['Low','Mid','High','High']})

In [12]:
sal_data

Salary Range
0   20000   Low
1   40000   Mid
2   60000  High
3   70000  High

In [19]:
a=salary_data.Range.map({'Low':'I','Mid':'II','High':'III'})

In [20]:
a

0      I
1     II
2    III
3    III
Name: Range, dtype: object

In [21]:
salary_data.Name.map({'Mani':'Nandy','Niswan':'Vasanth','Sriram':'Sutharson','Madesh':'Basith'})

0        Nandy
1      Vasanth
2    Sutharson
3       Basith
Name: Name, dtype: object

# NORMALIZATION

In [22]:
pip install matplotlib

  Using cached matplotlib-3.7.1-cp39-cp39-win_amd64.whl (7.6 MB)
  Using cached Pillow-9.4.0-cp39-cp39-win_amd64.whl (2.5 MB)
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
  Using cached contourpy-1.0.7-cp39-cp39-win_amd64.whl (160 kB)
     ---------------------------------------- 1.0/1.0 MB 4.0 MB/s eta 0:00:00
  Using cached kiwisolver-1.4.4-cp39-cp39-win_amd64.whl (55 kB)
Note: you may need to restart the kernel to use updated packages.


In [26]:
pip install scikit-learn

     ---------------------------------------- 8.4/8.4 MB 9.9 MB/s eta 0:00:00
     -------------------------------------- 298.0/298.0 kB 6.1 MB/s eta 0:00:00
     ---------------------------------------- 42.5/42.5 MB 8.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [55]:
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

In [56]:
import numpy as np
import pandas as pd

In [57]:
norm=pd.DataFrame({'x':np.random.randint(-100,100,5000),
                  'y':np.random.randint(-200,100,5000),
                  'z':np.random.randint(0,1000,5000)})

In [58]:
norm

x    y    z
0    -49  -25    7
1     10    5  855
2      6  -61  895
3    -63  -89  584
4     93  -22  879
...   ..  ...  ...
4995 -35 -134  849
4996  19  -48  765
4997  -5   -5  985
4998 -53 -176  160
4999   8 -155  177

[5000 rows x 3 columns]

In [59]:
ax=plt.axes(projection='3d')
ax.scatter3D(norm.x,norm.y,norm.z)
plt.figure()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [60]:
from sklearn.preprocessing import Normalizer

In [61]:
normal=Normalizer()

In [62]:
norm=normal.fit_transform(norm)

In [63]:
norm

array([[-0.88363624, -0.45083482,  0.12623375],
       [ 0.01169491,  0.00584745,  0.99991451],
       [ 0.00668824, -0.06799715,  0.9976631 ],
       ...,
       [-0.00507601, -0.00507601,  0.99997423],
       [-0.2174891 , -0.72222794,  0.65657086],
       [ 0.03398322, -0.65842494,  0.7518788 ]])

In [65]:
norm_mn=pd.DataFrame(norm,columns=['A','B','C'])

In [66]:
norm_mn

A         B         C
0    -0.883636 -0.450835  0.126234
1     0.011695  0.005847  0.999915
2     0.006688 -0.067997  0.997663
3    -0.106044 -0.149808  0.983012
4     0.105182 -0.024882  0.994142
...        ...       ...       ...
4995 -0.040687 -0.155774  0.986954
4996  0.024780 -0.062603  0.997731
4997 -0.005076 -0.005076  0.999974
4998 -0.217489 -0.722228  0.656571
4999  0.033983 -0.658425  0.751879

[5000 rows x 3 columns]

In [69]:
bx=plt.axes(projection='3d')
bx.scatter3D(norm_mn.A,norm_mn.B,norm_mn.C)
plt.figure()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

# Data sorting

In [70]:
data=[4,64,65,32,87,23,66,97,21,43,67,89,10,6,8]

In [71]:
data.sort()
print(data)

[4, 6, 8, 10, 21, 23, 32, 43, 64, 65, 66, 67, 87, 89, 97]


In [72]:
data.reverse()
print(data)

[97, 89, 87, 67, 66, 65, 64, 43, 32, 23, 21, 10, 8, 6, 4]


# Missing vales

In [100]:
import numpy as np
import pandas as pd

In [101]:
data={'I score':[54,np.nan,54,np.nan],
     'II score':[65,76,87,np.nan],
     'III score':[82,43,np.nan,np.nan]}

In [102]:
score=pd.DataFrame(data)

In [103]:
score

I score  II score  III score
0     54.0      65.0       82.0
1      NaN      76.0       43.0
2     54.0      87.0        NaN
3      NaN       NaN        NaN

In [104]:
score.isnull()

I score  II score  III score
0    False     False      False
1     True     False      False
2    False     False       True
3     True      True       True

In [105]:
score.isnull().sum()

I score      2
II score     1
III score    2
dtype: int64

In [106]:
from sklearn.impute import SimpleImputer

In [107]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [108]:
imputer.fit(score)

SimpleImputer()

In [109]:
imputer.transform(score)

array([[54. , 65. , 82. ],
       [54. , 76. , 43. ],
       [54. , 87. , 62.5],
       [54. , 76. , 62.5]])

In [110]:
imputermedian=SimpleImputer(missing_values=np.nan,strategy='median')

In [111]:
imputermedian.fit(score)

SimpleImputer(strategy='median')

In [112]:
imputermedian.transform(score)

array([[54. , 65. , 82. ],
       [54. , 76. , 43. ],
       [54. , 87. , 62.5],
       [54. , 76. , 62.5]])