In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
c=np.array([(1,2,3,4),(9,8,7,6)])

In [6]:
print(c)

[[1 2 3 4]
 [9 8 7 6]]


In [7]:
C=np.transpose(c)

In [8]:
print(C)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [9]:
C.ravel()

array([1, 9, 2, 8, 3, 7, 4, 6])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
ze=np.zeros((1,4))

In [13]:
print(ze)

[[0. 0. 0. 0.]]


In [14]:
ze=np.zeros((4,4))

In [15]:
print(ze)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ze.resize(10,1)

In [17]:
print(ze)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [18]:
np.append(C,ze)

array([1., 9., 2., 8., 3., 7., 4., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
mad=np.insert(a,4,5)

In [21]:
mad

array([1, 2, 3, 4, 5])

In [22]:
mas=np.delete(a,[1])

In [23]:
mas

array([1, 3, 4])

In [24]:
txt=np.array([(1,2),(5,8)])

In [25]:
txt

array([[1, 2],
       [5, 8]])

In [30]:
np.concatenate((txt,txt),axis=None)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [27]:
np.hstack((txt,txt))

array([[1, 2, 1, 2],
       [5, 8, 5, 8]])

In [29]:
np.vstack((txt,txt))

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [34]:
np.vsplit(txt,2)

[array([[1, 2]]), array([[5, 8]])]