In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])

In [6]:
print(a)

[1 2 3 4]


In [8]:
c=np.array([(1,2,3,4),(9,8,7,6)])

In [9]:
print(c)

[[1 2 3 4]
 [9 8 7 6]]
